# Qbe iLogin Makefile: QbeHTA
# Copyright (C) 2001-2003 Christian Hofstaedtler.  All rights reserved.
#

## -> MFC
#QBECLIB=-D_MD -MD /D "_AFXDLL"
QBEPROG=QbeSAS
QBEPEXT=DLL
# QBEPOBJ=QbeStart.exe
QBEEXTRAALL=
QBEEXTRALINK=
QBEEXTRALINKDEP=
QBEWINSYS=windows
WITHSSL=
WITHNETLIB=no
QBENETCOMPILER=csc
QBENETTARGET=library

PROG_FILES = ..\Common\AssemblyInfo.cs \
	..\Common\Conform.cs \
	DataStore.cs

#QBECUSTOMLINK=csc /target:library /out:$(OUTDIR)\$(QBEPROG).$(QBEPEXT) $(PROG_FILES) 

!include "../Common/ilogin.mak"


# - eof -

