<div class="allgemein" id=menu-allgemein>
<center>
<table border=0 width=200 cellspacing=0 cellpadding=0>
	<tr height=50><td onmouseover='hoover_in(this,"#999999");' onclick='jump("cal2.php?Abteilung=0");' onmouseout='hoover_out(this,"#000000");'><center>Kalender</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#999999");' onclick='jump("news.php?Abteilung=0&Type=Abteilung");' onmouseout='hoover_out(this,"#000000");'><center>Infos</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#999999");' onclick='jump("http://www.htlwrn.ac.at/~e99163/");' onmouseout='hoover_out(this,"#000000");'><center>Wetterstation</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#999999");' onclick='jump("http://www.htlwrn.ac.at/~e99163/");' onmouseout='hoover_out(this,"#000000");'><center>Energiesystem</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#999999");' onclick='jump("teachersearch.php");' onmouseout='hoover_out(this,"#000000");'><center>Lehrersuche</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#999999");' onclick='jump("login.php");' onmouseout='hoover_out(this,"#000000");'><center>Logout</center></td></tr>
</table>
</center>
</div>
<div class="etechnik" id="menu-etechnik">
<center>
<table border=0 width=200 cellspacing=0 cellpadding=0>
	<tr height=50><td onmouseover='hoover_in(this,"#ffffff");' onclick='jump("cal2.php?Abteilung=1");' onmouseout='hoover_out(this,"#000000");'><center>Kalender</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#ffffff");' onclick='jump("news.php?Abteilung=1&Type=Abteilung");' onmouseout='hoover_out(this,"#000000");'><center>Infos</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#ffffff");' onclick='jump("av.php?Abteilung=1");' onmouseout='hoover_out(this,"#000000");'><center>AV-Stellvertreter</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#ffffff");' onclick='jump("stundenplan.php?Abteilung=1");' onmouseout='hoover_out(this,"#000000");'><center>Stundenplan</center></td></tr>
</table>
</center>
</div>
<div class="atechnik" id="menu-atechnik">
<center>
<table border=0 width=200 cellspacing=0 cellpadding=0>
	<tr height=50><td onmouseover='hoover_in(this,"#ffffff");' onclick='jump("cal2.php?Abteilung=2");' onmouseout='hoover_out(this,"#000000");'><center>Kalender</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#ffffff");' onclick='jump("news.php?Abteilung=2&Type=Abteilung");' onmouseout='hoover_out(this,"#000000");'><center>Infos</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#ffffff");' onclick='jump("av.php?Abteilung=2");' onmouseout='hoover_out(this,"#000000");'><center>AV-Stellvertreter</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#ffffff");' onclick='jump("stundenplan.php?Abteilung=2");' onmouseout='hoover_out(this,"#000000");'><center>Stundenplan</center></td></tr>
</table>
</center>
</div>
<div class="hochbau" id="menu-hochbau">
<center>
<table border=0 width=200 cellspacing=0 cellpadding=0>
	<tr height=50><td onmouseover='hoover_in(this,"#ffffff");' onclick='jump("cal2.php?Abteilung=4");' onmouseout='hoover_out(this,"#000000");'><center>Kalender</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#ffffff");' onclick='jump("news.php?Abteilung=4&Type=Abteilung");' onmouseout='hoover_out(this,"#000000");'><center>Infos</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#ffffff");' onclick='jump("av.php?Abteilung=4");' onmouseout='hoover_out(this,"#000000");'><center>AV-Stellvertreter</center></td></tr>
	<tr height=50><td onmouseover='hoover_in(this,"#ffffff");' onclick='jump("stundenplan.php?Abteilung=4");' onmouseout='hoover_out(this,"#000000");'><center>Stundenplan</center></td></tr>
</table>
</center>
</div>