#!/usr/bin/perl -w

system("/opt/qbe/qbeservice start");
system("/bin/sleep 2");

my $user = `gconftool-2 -g /apps/qbe/username`;
my $pass = `gconftool-2 -g /apps/qbe/password`;

if ( ($user eq '') || ($pass eq '') )
{
	print "Error: No username or password configured!";
	exit;
}

use LWP::UserAgent;
my $url = 'http://127.0.0.1:7666/web/hta-login-post?user=' . $user . '&pass=' . $pass;

my $ua = LWP::UserAgent->new;
$ua->timeout(10);

my $response = $ua->get($url);

print "Qbe Client response: ".$response->status_line."\n";

