#!/bin/sh
### BEGIN INIT INFO
# Provides:          qbeservice
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: Qbe SAS Client
# Description:       The startup file for Qbe SAS Client
### END INIT INFO
# $Id$

set -e

PATH=/opt/qbe:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="Qbe SAS Client"
NAME=QbeService
DAEMON=/opt/qbe/$DAEMON
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

d_start() {
  start-stop-daemon --start --quiet --pidfile $PIDFILE \
	  --exec $DAEMON --pidfile $PIDFILE --uid 65534 --gid 65534 \
	  || echo -n " already running"
}

d_stop() {
  start-stop-daemon --stop --quiet --pidfile $PIDFILE \
	  --name $NAME \
	  || echo -n " not running"
}
					
case "$1" in
  start)
	echo -n "Starting $DESC: $NAME"
	d_start
	echo "."
	;;
  stop)
	echo -n "Stopping $DESC: $NAME"
	d_stop
	echo "."
	;;
	restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: $NAME"
	d_stop
	sleep 1
	d_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0

